
title: Apolinario Miguel Tan
email: atan@sissa.it
description: >- # this means to ignore newlines until "baseurl:"
  Write a brief description of your site here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: your-twitter-handle
github_username:  apolmiguel

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed